# Generated by Django 3.2.11 on 2022-02-06 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('carType', models.CharField(max_length=100)),
                ('noOfSeats', models.IntegerField()),
                ('gearBox', models.CharField(max_length=250)),
                ('fuel', models.CharField(max_length=250)),
                ('photo1', models.ImageField(upload_to='cars/')),
                ('photo2', models.ImageField(upload_to='cars/')),
                ('photo3', models.ImageField(upload_to='cars/')),
                ('city', models.CharField(max_length=250)),
                ('address', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('cleaningFee', models.FloatField()),
                ('monthlyDiscount', models.IntegerField()),
                ('weeklyDiscount', models.IntegerField()),
                ('listingTitle', models.CharField(max_length=250)),
                ('listingDescription', models.TextField(max_length=3000)),
                ('rules', models.TextField(max_length=3000)),
                ('checkIn', models.CharField(max_length=250)),
                ('checkOut', models.CharField(max_length=250)),
                ('rentalPeriod', models.CharField(max_length=250)),
                ('status', models.TextField(default='In Progress', max_length=200)),
                ('amenities', models.ManyToManyField(null=True, to='webapp.AmenitiesModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contactNo', models.CharField(max_length=255)),
                ('password', models.TextField(max_length=2255)),
                ('DOB', models.CharField(max_length=255)),
                ('token', models.CharField(default='', max_length=255)),
                ('profile', models.ImageField(default='profile/default_avatar.jpg', upload_to='profile/')),
                ('status', models.CharField(default='disable', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('companyName', models.CharField(max_length=250)),
                ('contactNo', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.TextField(max_length=3000)),
                ('description', models.TextField(blank=True, default='', max_length=3000)),
                ('profile', models.ImageField(default='profile/default_avatar.jpg', upload_to='profile/')),
                ('status', models.CharField(default='disable', max_length=50)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1500)),
                ('date', models.DateField(auto_now_add=True)),
                ('carid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.carsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=550)),
                ('lastName', models.CharField(default='', max_length=550)),
                ('contactNo', models.CharField(default='', max_length=550)),
                ('Pickup', models.TextField(default='', max_length=550)),
                ('Return', models.TextField(default='', max_length=550)),
                ('checkIn', models.CharField(default='', max_length=250)),
                ('checkOut', models.CharField(default='', max_length=250)),
                ('BookDateandtime', models.DateTimeField(auto_now_add=True)),
                ('returnCar', models.CharField(default='No', max_length=10)),
                ('totalPrice', models.FloatField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending payment', 'Pending payment'), ('Completed', 'Completed'), ('Cancel', 'Cancel')], default='Processing', max_length=100)),
                ('bookBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.usermodel')),
                ('car', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.carsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='vendorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.vendormodel'),
        ),
    ]
