# Generated by Django 3.2.11 on 2022-02-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_reviewsmodel_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsmodel',
            name='firstName',
            field=models.CharField(default='', max_length=550),
        ),
        migrations.AddField(
            model_name='reviewsmodel',
            name='lastName',
            field=models.CharField(default='', max_length=550),
        ),
    ]
