# Generated by Django 3.2.11 on 2022-02-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20220207_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='email',
            field=models.CharField(default='', max_length=550),
        ),
    ]
