# Generated by Django 3.2.11 on 2022-02-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20220207_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModels',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=255)),
            ],
        ),
    ]
