# Generated by Django 3.2.11 on 2022-02-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_citymodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.citymodels'),
        ),
    ]
