# Generated by Django 3.2.11 on 2022-03-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_vendormodel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='monthlyDiscount',
        ),
        migrations.RemoveField(
            model_name='carsmodel',
            name='weeklyDiscount',
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='address',
            field=models.TextField(default='null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='city',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
