# Generated by Django 3.2.11 on 2022-03-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_carsmodel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='city',
        ),
    ]
