# Generated by Django 3.2.11 on 2022-03-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_carsmodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='city',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
